### ISSUE TITLE
Establish development requirements for redirects

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/web-redesign#173]
As a Libraries Web Stakeholder, I want to preserve the links from my external site to the main site, so that I can minimize disruption to key user flows while my site remains on the Library Template.

**Comment by laurenhamel** [comment]
@nikdragovic and @kristianserrano, I'm thinking this should be converted into an epic since it alludes to work that will need to be done in both the templating engine and CMS. For the templating engine, we'll need to make sure that we're looking for and processing redirects in the right places and ways, and for Cascade, we'll likely need to build out content type(s) for redirects and figure out how we want to manage that.

**Comment by kristianserrano** [comment]
Agreed. Making it an Epic now.

**Comment by nikdragovic** [comment]
Thanks, makes sense to me.

**Comment by laurenhamel** [comment]
As we move into Phase 2, this is no longer related to the templating engine. This mostly involves collaborating with Middleware to make sure that redirects are in place once we go live, which is work that is being captured in the project's WBS instead.
