### ISSUE TITLE
"Select a Library" in header should read "Select a Location"

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/web-redesign#212]
I have corrected the dropdown list, which was originally filler data, but I cannot figure out how to edit the header text itself in Cascade.

**Comment by laurenhamel** [comment]
The "Select a Library" text was hard-corded into the branding pattern because we needed to set a fixed width for the select menu based on the default text that was shown in order to prevent the menu's arrow icon from drifting too far way from the text. This would need to be changed in the Pattern Library.

**Comment by laurenhamel** [comment]
This should be fixed in the `interim/static-preview-site` branch.

**Comment by laurenhamel** [comment]
This was completed and moved to Phase 2.
