### ISSUE TITLE
Pattern Library: Incorporate Related Content Organism into Cover Page Template

### ISSUE THREAD

**Issue by rosy1280** [emory-libraries/web-redesign#216]
Above the feeds section of the Cover Template, add in the [Related Content Organism](https://www.figma.com/file/avklVGwesTU6PIw6BM1dmTvl/Pattern-Modeling?node-id=42%3A143)

- [x] Related Content Section should have a header above it similar to what you see on the [Landing Page](https://www.figma.com/file/avklVGwesTU6PIw6BM1dmTvl/Pattern-Modeling?node-id=51%3A2525)
- [x] Related Content Section should appear above the header for Header for feeds.

**Comment by rosy1280** [comment]
Related to #218

**Comment by laurenhamel** [comment]
@rosy1280, in reviewing the pattern library's handlebar templates, there's a lot of code pertaining to the inline mutations that we were doing for the templating engine. This is mostly markup related to how we were performing values checks, renaming properties, restructuring the data model, etc. due to the discrepancies that exist between the Cascade data definitions and the data model used by our pattern library templates. (It may also be worth noting is that additional mutations were performed within the templating engine as well to essentially "normalize" the data models.) I'm wondering if you think it makes sense to go ahead and remove this extra code (which feels bloated and adds noise to the actual handlebars pattern as well as has no impact on rendering inside the pattern library) at this time?

**Comment by laurenhamel** [comment]
I went ahead and commented out any templating engine stuff that was inside the template files while adding in the related section to the cover page template. I'm creating a "Pending" column for the time being as a place to drop cards that have been worked on and completed but will need to be deployed to the pattern library then reviewed.

**Comment by rosy1280** [comment]
@laurenhamel can you go ahead and just delete it altogether? That will make it easier on Hannon Hill. And thanks for catching that!
