### ISSUE TITLE
Data Definitions: Incorporate Related Content (aka Research Aids) into Cover Page Template

### ISSUE THREAD

**Issue by rosy1280** [emory-libraries/web-redesign#218]
Using the Research Aids Section modeled on the Landing Page, add Research Aids to the Cover Page Template

- [x] The header for the Research Aids Section should be fixed to Get Help Using the Library
- [x] Ensure users can add any number of Research Aid Links
- [x] Research Aid Links should only link to pages within Cascade
- [x] Content creators should be able to customize the label for the Research Aid Link; otherwise the label should pull from the Cascade page's title

**Comment by rosy1280** [comment]
@laurenhamel a few question: 

- Does the header have to be fixed?
- There is a version number, can you help me understand what's that for?

**Comment by laurenhamel** [comment]
@rosy1280, the header does not have to be fixed, but a default can be set in both the CMS and the template, which is how it's setup currently. The version numbers exist only as a reference for the web developers to better understanding the current state of the data definition as it relates to the pattern library: That is, its primarily implemented for scalability as a way for us to be able to constantly check against the data definition's version or sub-pattern version within the data definition in order to make sure data is available and fields are consistently handled even as DDs evolve and change. From a pattern library perspective, it serves to help us synchronize templates and patterns with data definitions as any changes may occur with the PL as well. It's worth mentioning that only Cascade users with a high enough level of access rights should be able to edit the version fields.

**Comment by laurenhamel** [comment]
These fixes have been applied to both the Cover Page and Homepage DDs in Cascade.

**Comment by rosy1280** [comment]
Thanks @laurenhamel that's helpful to know. Let's talk with Hannon Hill about how we can keep that sentiment even if we don't keep the exact process.
