### ISSUE TITLE
Pattern Library: Incorporate Related Content (aka Research Aids) into Home Page Template

### ISSUE THREAD

**Issue by rosy1280** [emory-libraries/web-redesign#220]
Below the Slider section of the [Home Page Template](http://template.library.emory.edu/styleguide/patternlibrary/current/?p=templates-home), add in the [Related Content Organism](https://www.figma.com/file/avklVGwesTU6PIw6BM1dmTvl/Pattern-Modeling?node-id=42%3A143)

- [x] Related Content Section should have a header above it similar to what you see on the [Landing Page](https://www.figma.com/file/avklVGwesTU6PIw6BM1dmTvl/Pattern-Modeling?node-id=51%3A2525)
- [x] Related Content Section should appear above the content well.

Compare the Pattern Library's [Home Page Template](http://template.library.emory.edu/styleguide/patternlibrary/current/?p=templates-home) to Figma's [Home Page Template](https://www.figma.com/file/avklVGwesTU6PIw6BM1dmTvl/Pattern-Modeling?node-id=51%3A2525)

**Comment by laurenhamel** [comment]
I went ahead and grouped this fix with the cover page template fix (#216) since they were dealing with the same content pattern. Turns out, the related section was already built into the home page pattern, and the pattern library was only missing some placeholder data in order to get this section to display.

**Comment by rosy1280** [comment]
@laurenhamel thanks!
