### ISSUE TITLE
Pattern Library: Optimize CSS and JS

### ISSUE THREAD

**Issue by rosy1280** [emory-libraries/web-redesign#223]
Right now the [CSS](https://template.library.emory.edu/styleguide/patternlibrary/releases/1.0.0-dev.6/css/style.min.css) used by the QA site takes several seconds to load.  Running Google Lighthouse indicates some performance issues.  Determine how we can address these issues.  Possible questions:

- [x] Remove unused CSS
- [x] Remove unused JS
- [x] Review errors in the JS; improve where possible

**Comment by laurenhamel** [comment]
I optimized the CSS and was able to do some refactoring, disabling and excluding styles that are not currently in use, and other slight modifications, which seemed to reduce the total file size to around ~650kb. I was also able to remove some of the JS code related to some of the unused patterns, which reduced the overall JS file size just slightly, but the file still remains relatively large because its bundling in client-side dependencies such as jQuery and Lodash in addition to a few others. 

As far as the JS errors that are occurring in the `qa` environment, I'm unable to identify the root cause of the issue at this time because I'm unable to reproduce the same issue locally and also don't see the same errors getting thrown on the `preview` domain. I can determine that the error is related to the use of `LocalStorage` for storing session data, but I'm not entirely sure why only the `qa` environment is being finicky. We'll have to continue to monitor this for now to see if the issue occurs later.
