### ISSUE TITLE
Pattern Library: Update Hours Template

### ISSUE THREAD

**Issue by rosy1280** [emory-libraries/web-redesign#224]
Update the hours page to include a regular hours section.

- [x] Upcoming hours gets their own header
- [x] Upcoming hours should only display building hours
- [x] Upcoming hours should display as it currently does
- [x] Regular hours gets their own header
- [x] A drop down should allow users to choose regular hours based on semester (Fall Term, Winter Intersession, Spring Term, Summer Term, Summer Intersession); note that this will not always include all the terms.
- [x] A button group should allow users to jump to the library hours of their choosing
- [x] Tables should appear allowing users to see regular hours for the week.
- [x] Mobile view should allow users to scroll through the regular hours table by day of the week, similar to the pattern on the upcoming hours.

**Comment by rosy1280** [comment]
![hours-mockup](https://user-images.githubusercontent.com/143322/65293211-691a0b00-db28-11e9-97b9-83fe0d6a3f0c.png)

**Comment by laurenhamel** [comment]
@rosy1280, as I was updating the Figma design for the hours page, I reviewed the existing hours page again and was thinking about some minor changes that could be made to the mockup above to capture move information with a smaller footprint while keeping with the new pattern designs. I wanted to run this design idea by you to see what you'd think:

<img width="524" alt="Screen Shot 2019-09-26 at 8 46 13 AM" src="https://user-images.githubusercontent.com/24446243/65689467-25993280-e03b-11e9-9cef-859cde4d793c.png">

The main changes that you'll notice are the "Select a Location" buttons to toggle between the various locations' hours tables and the two different links for "Full Schedule of Hours" (which would link out to a complete schedule of hours for that semester) and "Library Master Schedule" (which could be optional and link out to a master schedule of hours for the selected library if available).

**Comment by rosy1280** [comment]
@laurenhamel I love the design! A question for you: does the data definition allow us to group service points by building?

The only thing I would change is that ECDS is a service point so we'd want to remove them from the filters and show them as a service point in a building.

**Comment by laurenhamel** [comment]
I updated both the styles and template for the hours page to reflect the changes we've made to the hours data definition. One thing worth noting about the new page design: Because the regular hours content section relies on the two controls (i.e., dropdown for semester and button for location), by default, it's setup as a Vue.js component. Since we need those two values to populate the table, there isn't really a clean way to display this same design when JavaScript is disabled, so I merely setup the `noscript` fallback to display a message that reads "Please enable JavaScript..." I noticed that this is also what [Arizona](https://test.library.arizona.edu/hours) is doing in their new design that you shared with me. The only real alternative to this sort of error message would be the same approach that we're kind of wanting to avoid, where we would need to display all regular hours tables for each location grouped by semester.
