### ISSUE TITLE
Build out Calendar Event Page

### ISSUE THREAD

**Issue by rosy1280** [emory-libraries/web-redesign#228]
See Figma design.  Highlights:

- [x] Title of page should be centered
- [x] Content should be grouped by month
- [x] Month label should be centered
- [x] One box per calendar event should appear grouped under its month
- [x] Each event should have an image; events without image should default to ??
- [x] A date for the event should appear below the image and above the title
- [x] The title for the event should appear below the date

**Comment by laurenhamel** [comment]
I ended up reworking some of the preprocessing stuff that's needed for grouping and sorting events and exhibits by dates and moved all of that logic into handlebars helpers (previously existed as inline mutations within the patterns themselves, which added a lot of mess). This now creates the Calendar page and helps to cleanup all other events and exhibits pages. These changes should also fix any grouping and sorting issues we were seeing previously within these pages.

**Comment by laurenhamel** [comment]
Also, I reached out to James to see if about getting the `GD` module for PHP installed on the old server where `template.library.emory.edu` is currently housed because I setup a `gradient.php` file that requires `GD` be enabled. This `gradient.php` file will allow us to dynamically create a gradient image as a placeholder whenever a tile or card is missing a designated image.
