### ISSUE TITLE
Remove embedded svgs

### ISSUE THREAD

**Issue by rosy1280** [emory-libraries/web-redesign#230]
Update CSS to accommodate the switching embedded SVGs to images.

**Comment by rosy1280** [comment]
@laurenhamel if there is anything i can do to help with creation of an inventory or similar let me know.

**Comment by laurenhamel** [comment]
@rosy1280, I think an inventory would be useful. I'll start a checklist and add places that I can think of off the top of my head where I know have icons that will need updating.

**Comment by laurenhamel** [comment]
This is done. Instead of converting all SVGs to images, we opted to create an SVG image sprite instead. The main issue we were running into was that, while building out the formats in Cascade, Hannon Hill did not have a way to code for selectable icons using the existing inline SVG style. Instead of relying on the `icon.php`, a better solution was to compile all SVGs into a single sprite sheet, where we could then `<use>` any icon by simply supplying the icon's ID (e.g., `#material-lightbulb`).
