### ISSUE TITLE
Create Production Environment

### ISSUE THREAD

**Issue by rosy1280** [emory-libraries/web-redesign#238]
- [x] set up prod.libraries.emory.edu as the production environment for the website.
- [x] Cascade `Publish to Production` should publish to prod.libraries.emory.edu.
- [x] preview.libraries.emory.edu should remain in place through launch.
- [x] Remove `Publish to Production root` from Cascade
- [x] copy CSS and JS to prod.libraries.emory.edu
- [x] ensure that only LTDS staff and Colin Bragg can publish to the production environment.
- [x] ensure ssl certs are properly configured

**Comment by jamesbiasemory** [comment]
currently prod.libraries still has the copy of preview in it, so it should have the CSS and JS, if I am not correct please let me know. 
The only thing that still needs to be done that didn't make it to the list and slipped by me was adding prod.libraries.emory.edu to the SSL cert, I will get that taken of Monday. 
Everything else should be done.

**Comment by rosy1280** [comment]
@jamesbiasemory just to make sure i'm clear.  If i publish to prod.libraries will i overwrite preview.libraries?  because the goal is to keep those two domains separate i.e. if i publish to prod preview should stay as it currently is.

**Comment by jamesbiasemory** [comment]
no, I have made a separate directory for preview.libraries.  I have not setup a destination to it because I thought it would remain unchanged. Although I can setup a destination for preview if you need it.  
if you publish to prod it will go in the libraries.emory.edu directory which prod.libraries points to as a server alias, so when we go live all that needs to be done is point the domain name to the new server.

**Comment by rosy1280** [comment]
@jamesbiasemory ok good.  that's what i thought you meant, but i wanted to make sure.  out of an abundance of caution, i'm going to wait until monday morning to publish to prod though....
