### ISSUE TITLE
Hours Not Displaying on the Homepage

### ISSUE THREAD

**Issue by rosy1280** [emory-libraries/web-redesign#283]
The [hours for Woodruff Library Building](https://libraries.emory.edu/hours/index.html) are not displaying on the [homepage](https://libraries.emory.edu/) under the Visit Us heading.  The homepage for the website did display the current day's hours for the Woodruff Library Building, we aren't clear about when it stopped displaying because it happened during the pandemic when the building was closed.

**Comment by rosy1280** [comment]
when the building is marked closed altogether, the hours on the homepage indicate that the building is closed.

**Comment by LadySnowy** [comment]
@rosy1280 There were 2 issues, actually easy to fix once I tracked them down.

1. The wrong page was selected for the hours on the homepage. The hours/index page was selected, instead of one of the hours data pages found in _shared/hours. I selected the Woodruff Library Building; I hope that was correct.
2. The data definition was updated at some point to have lowercase values for the Freeform/Structured radio option. I updated those in the #getTime macro of [this](https://cascade.emory.edu/entity/open.act?id=acad04990ae7209815168d8ac209dbda&type=format) format, lines 536 & 545.
