### ISSUE TITLE
Host pattern library on public domain

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/web-redesign#99]
Upload current pattern library code for stakeholder review.

Current pattern library: http://template.library.emory.edu/styleguide/patternlibrary/current/

- [x] Develop deployment process
- [x] Deploy to template.library.emory.edu/styleguide/patternlibrary

**Comment by nikdragovic** [comment]
Do we need to discuss how we'll relate Pattern Lab to Style Guide Guide? I found the following reference that just says a straightforward import is "coming soon."

https://github.com/bradfrost/gatsby-style-guide-guide

**Comment by laurenhamel** [comment]
@nikdragovic, that functionality hasn't quite been built into the native Style Guide Guide implementation that Brad Frost created, but I've already made the necessary modifications to be able to export patterns from our Pattern Library into our custom instance of Style Guide Guide. That is, it's already been set it up for our specific workflow, including some reorganizing of the folder and file structure to better suite our needs in terms of the type of information we might be storing in there. Feel free to poke around our [style-guide-guide](https://github.com/emory-libraries/style-guide-guide) repo and let me know your thoughts.

**Comment by nikdragovic** [comment]
@laurenhamel Excellent, thank you so much! Tsk to me for not checking there first; this is very helpful:

Brad Frost created Style Guide Guide as a quick and dirty way to build documentation for design systems based on his arguments about workshops vs. storefronts. It's intended to be used as a storefront for showcasing patterns from Pattern Lab, where Pattern Lab is the workshop. For additional information about Style Guide Guide, visit to the original Style Guide Guide repo by Brad Frost on Github.

**Comment by kristianserrano** [comment]
Additionally, @nikdragovic, as we discussed earlier, the Style Guide Guide will sit at https://template.library.emory.edu/styleguide/ and the pattern library will sit at https://template.library.emory.edu/styleguide/patternlibrary which redirects to https://template.library.emory.edu/styleguide/patternlibary/current.

The "current" subdirectory is simply a symlink that references the latest release of the pattern library and is updated during deployment. The folder structure for releases looks like this:
![Screen Shot 2019-03-22 at 9.42.54 AM.png](https://images.zenhubusercontent.com/5b870487d5262f371e9eac64/5ade40fa-0fbe-4c0e-a2d4-d5e400354d55)

**Comment by laurenhamel** [comment]
@kristianserrano, I'm wondering if we should go ahead and archive the older pattern library versions and start fresh in our releases folder. Our new pattern library versions will start back at `1.0.0`, so it may be necessary to avoid any confusion. Since what we share now will only be for demoing purposes, we may also want to drop it in the release folder with just a generic `dev` version tag.

**Comment by kristianserrano** [comment]
In some way, we should keep the older one available. Some of the ETD styles are based on the patterns in there, and if they need to add something, they might want to refer to it.

My proposal is to keep the versioning going. and we can designate it as 2.0.0-alpha to show that it's under development. We can keep current pointing to 1.2.2 in the meantime.

We also never got around to modifying the index page to list the versions with links to each. If we did that, we could list the 2.0.0-alpha for people to access it.

I'm open to being told I'm wrong.

**Comment by laurenhamel** [comment]
Since we ended up doing a "hard reset" for the pattern library repo, I'm somewhat leaning towards doing the same thing here to keep our versioning clean and concise between the repo. Would it be a bad idea if we just rename the existing directory to `patternlibrary-legacy` and start fresh in the `patternlibrary` folder  to kind of mimic what we did with the repo?

**Comment by kristianserrano** [comment]
I see where you're coming from. We did do a hard reset, but we also still have the past tagged releases in that same repo.

Eventually, the new version will be another tagged release in the same repo. There's no harm in making it's version number 2.0.0. Also, keeping a list of links to all versions in one place and with a consistent naming pattern would help.

I guess I'm not seeing what gain there is in resetting to version 1.0.0 whereas I think a version 2.0.0 clearly communicates a relationship within the repo itself.

**Comment by nikdragovic** [comment]
This all sounds good and gives me the information I need at this time. I was going to ask about deployment of new code to the pattern library, so that one is answered.

I am happy with whatever path you take on versioning, as long as we maintain the current pattern library and have the new one tagged as under development.

**Comment by laurenhamel** [comment]
Really, the only dilemma I see that may cause confusion is that we now have the sass framework version, which is also reflecting the new pattern library version. If we wanted to keep those in sync (bumping the framework's version each time we bump the pattern library version), then we'd have to move everything up to `2.0.0` to begin with, which, to me, just felt weird. Otherwise, if we're not concerned about keeping things in sync at the repo level, we'll likely just have to more strict about versioning the patterns themselves.

**Comment by kristianserrano** [comment]
Oh! So let me know if I have this right. You were going to sync the version numbers between the Sass library and the pattern library. So rather than have a pattern library at v2.0.0 using a Sass library at 1.0.0, you wanted to match both of them up at 1.0.0. Do I have that right?

If so, what happens when we change a mixin in the Sass that doesn't change anything in the pattern library? Do we still increment the pattern library to match so that they are always in sync?

**Comment by laurenhamel** [comment]
Right. That's kind of what I was envisioning, and if we change a component's mixin in the sass framework, we'll always have to update it in the pattern library anyway because it would always change whatever the compiled CSS output was, even for something minor.

**Comment by nikdragovic** [comment]
Sorry that we didn't cover this in sprint planning, but can the lead on this issue update the title, break out additional issues, and documents steps as checkboxes if necessary? When the decisions are made on how to proceed, it would be good to estimate the work, too?

**Comment by kristianserrano** [comment]
@nikdragovic We can do that, but I'd like for @laurenhamel and I to discuss in person on Monday before we start making changes to the board.

I think for deployment setup and execution, we can create separate issues and reference them in this issue either in the details or in the comments.

**Comment by nikdragovic** [comment]
@kristianserrano Sounds good! Let's check in at standup.

**Comment by kristianserrano** [comment]
@laurenhamel If you generate the pattern library as is (assuming master branch), I'll upload it to the web server.

**Comment by laurenhamel** [comment]
I've been working on the `web-redesign` branch (to avoid having to constantly submit PRs to merge commits). I can generate it, but it may be easier if I upload it on my end. @kristianserrano, if that works for you, just let me know where to put it.

**Comment by kristianserrano** [comment]
Yeah, that's fine. Let's put it here:
template.library.emory.edu/styleguide/patternlibrary/

You can purge everything except the legacy folder.

What are your thoughts on keeping future past versions available?

**Comment by laurenhamel** [comment]
I just finished setting up the deployment process and went ahead and deployed everything, so do check it and let me know if you run into any issues. @kristianserrano, I decided to create a `patternlab` subdirectory in addition to the `releases` one, so now we'll have a versioned record of each time we deploy the pattern library instance as well as released asset files (`js`, `css`, etc.).

**Comment by laurenhamel** [comment]
Also, I added in a `latest` symlink that points to the most recently deployed asset files in `releases`. The `current` symlink is still pointing to the most current pattern lab instance that gets deployed.
